// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID         pgtype.UUID
	FirstUser  pgtype.UUID
	SecondUser pgtype.UUID
	CreatedAt  pgtype.Timestamp
}

type Message struct {
	ID       pgtype.UUID
	Chat     pgtype.UUID
	Sender   pgtype.UUID
	Receiver pgtype.UUID
	Message  string
	SentAt   pgtype.Timestamp
}

type User struct {
	ID           pgtype.UUID
	Name         string
	Password     string
	Email        string
	RegisteredAt pgtype.Timestamp
}
