// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	err := row.Scan(&id)
	return id, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, name, email, registered_at FROM users
`

type GetAllUsersRow struct {
	ID           pgtype.UUID      `json:"id"`
	Name         string           `json:"name"`
	Email        string           `json:"email"`
	RegisteredAt pgtype.Timestamp `json:"registered_at"`
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.RegisteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, registered_at FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID           pgtype.UUID      `json:"id"`
	Name         string           `json:"name"`
	Email        string           `json:"email"`
	RegisteredAt pgtype.Timestamp `json:"registered_at"`
}

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.RegisteredAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users(
    id,
    name,
    password,
    email
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING (id, name, email, registered_at)
`

type InsertUserParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Password string      `json:"password"`
	Email    string      `json:"email"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.ID,
		arg.Name,
		arg.Password,
		arg.Email,
	)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const isUsedEmail = `-- name: IsUsedEmail :one
SELECT EXISTS (
    SELECT TRUE FROM users
    WHERE email = $1 LIMIT 1
)
`

func (q *Queries) IsUsedEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, isUsedEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const login = `-- name: Login :one
SELECT id, name, email, registered_at FROM users
WHERE email = $1 AND password = $2 LIMIT 1
`

type LoginParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginRow struct {
	ID           pgtype.UUID      `json:"id"`
	Name         string           `json:"name"`
	Email        string           `json:"email"`
	RegisteredAt pgtype.Timestamp `json:"registered_at"`
}

func (q *Queries) Login(ctx context.Context, arg LoginParams) (LoginRow, error) {
	row := q.db.QueryRow(ctx, login, arg.Email, arg.Password)
	var i LoginRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.RegisteredAt,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
    SELECT TRUE FROM users
    WHERE id = $1 LIMIT 1
)
`

func (q *Queries) UserExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
